// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoi34AOF6KtRgLP76bY-md_YKmDyMDMcM',
    appId: '1:63664431109:android:ec46a3cd0f5c06199bfc6c',
    messagingSenderId: '63664431109',
    projectId: 'loginauth-aece0',
    storageBucket: 'loginauth-aece0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOG92etwC3Fe8pMQOSkf3n6w_FnHdffQY',
    appId: '1:63664431109:ios:4af5b546befd16f49bfc6c',
    messagingSenderId: '63664431109',
    projectId: 'loginauth-aece0',
    storageBucket: 'loginauth-aece0.firebasestorage.app',
    androidClientId: '63664431109-roobpuqq1emjdigrevc49l9hhaj2aqes.apps.googleusercontent.com',
    iosClientId: '63664431109-ledk2roig4g6gvsr8nilc4lrid9gjgh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC66qM9rXMht2ac8ebY7iPxPZSp8u19KtY',
    appId: '1:63664431109:web:b36c1a9cd89f4a149bfc6c',
    messagingSenderId: '63664431109',
    projectId: 'loginauth-aece0',
    authDomain: 'loginauth-aece0.firebaseapp.com',
    storageBucket: 'loginauth-aece0.firebasestorage.app',
    measurementId: 'G-YZFPX6QCXD',
  );

}